### ISSUE TITLE
session.rb - pending_requests.any? - NoMethodError for nil:NilClass

### ISSUE THREAD

**Issue by epcim** [net-ssh/net-sftp#35]
I am getting `NoMethodError: undefined method`any?' for nil:NilClass`in`net-sftp-2.1.2/lib/net/sftp/session.rb:801`. 

What fills `pending_requests`? Is it desired to check it for nil?

I workarounded it by:
`/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb` at line 801 by adding `pending_requests = pending_requests ? pending_requests : {}`:

``` ruby
# Runs the SSH event loop while the given block returns true. This lets
      # you set up a state machine and then "fire it off". If you do not specify
      # a block, the event loop will run for as long as there are any pending
      # SFTP requests. This makes it easy to do thing like this:
      #
      #   sftp.remove("/path/to/file")
      #   sftp.loop
      def loop(&block)
        pending_requests = pending_requests ? pending_requests : {}
        block ||= Proc.new { pending_requests.any? }
        session.loop(&block)
      end
```

Original log from Backup gem:
Please see - https://github.com/meskyanichi/backup/issues/544

```
[2014/05/14 09:04:25][error] --- Wrapped Exception ---
[2014/05/14 09:04:25][error] NoMethodError: undefined method `any?' for nil:NilClass
[2014/05/14 09:04:25][error] 
[2014/05/14 09:04:25][error] Backtrace:
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:801:in `block in loop'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:220:in `preprocess'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:205:in `process'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:169:in `block in loop'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:169:in `loop'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:169:in `loop'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/net-sftp-2.1.2/lib/net/sftp.rb:35:in `start'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/backup-4.0.1/lib/backup/storage/sftp.rb:29:in `connection'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/backup-4.0.1/lib/backup/storage/sftp.rb:35:in `transfer!'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/backup-4.0.1/lib/backup/storage/base.rb:35:in `perform!'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/backup-4.0.1/lib/backup/model.rb:269:in `each'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/backup-4.0.1/lib/backup/model.rb:269:in `block in perform!'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/backup-4.0.1/lib/backup/model.rb:268:in `each'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/backup-4.0.1/lib/backup/model.rb:268:in `perform!'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/backup-4.0.1/lib/backup/cli.rb:153:in `perform'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/backup-4.0.1/bin/backup:5:in `<top (required)>'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/bin/backup:23:in `load'
[2014/05/14 09:04:25][error]   /opt/chef/embedded/bin/backup:23:in `<main>'
```

**Comment by kmwhite** [comment]
For whatever it's worth, I also ran into this issue when attempting to use the SFTP gem to transfer files off of an SSH server. Using a proper SFTP service fixed the issue.

**Comment by hosamaly** [comment]
This issue was fixed in v3.0.0 (commit 266e810c)
