### ISSUE TITLE
Uploading Directory Tree Fails ("no such file") when Subdirectory is Empty

### ISSUE THREAD

**Issue by coreypmurphy** [net-ssh/net-sftp#44]
Uploading (recursively) a directory tree containing files and subdirectories fails when an empty subdirectory is encountered.  In the error below, I'm uploading a "bare clone" of a new git repo.  The bare clone contains files and folders, one of which, "branches" is empty.

Net::SFTP::StatusException (Net::SFTP::StatusException mkdir /sftp_repo_testing/test.git/branches (2, "no such file"))
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:310:in `on_mkdir'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:307:in `to_proc'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `call'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `respond_to'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:948:in `dispatch_request'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:911:in `when_channel_polled'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:893:in `to_proc'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:311:in `call'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:311:in `process'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `preprocess'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `each'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `preprocess'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop_forever'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:203:in `wait'
  /Users/a028541/.rvm/gems/ree-1.8.7-2012.02/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:103:in `upload!'
  app/models/course.rb:243:in `do_git_operations'
  app/controllers/courses_controller.rb:225:in `generate_html'
  /Users/a028541/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /Users/a028541/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /Users/a028541/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /Users/a028541/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /Users/a028541/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/webrick/server.rb:162

**Comment by coreypmurphy** [comment]
Figured out the issue.  Not necessarily a problem with the gem per se however I'd like to recommend an update to the documentation.

My problem stemmed from the fact that I was trying to perform a recursive upload of a directory without the directory folder already existing on the remote.  My assumption was that the upload of "local directory" to "remote directory" would upload the contents of the directory as well as the directory itself.   For example:

sftp.upload!( /local/myfolder, /remote/myfolder ) 

The above code attempts to upload the contents of "myfolder" but excludes "myfolder" itself from the upload.

While technically speaking this was easy to overcome once I understood what was happening but it led to some lengthy debugging.  Hope this helps someone else.
