### ISSUE TITLE
Windows, ruby 2.3.3 (32bit), net-sftp 2.1.2 and Pageant don't play nicely

### ISSUE THREAD

**Issue by ccoenen** [net-ssh/net-sftp#64]
```
C:\Users\user\test> gem install net-sftp
Successfully installed net-sftp-2.1.2
1 gem installed

C:\Users\user\test> irb
irb(main):001:0> require 'net/sftp'
LoadError: cannot load such file -- dl/import
        from C:/Tools/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Tools/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Tools/Ruby23/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/pageant.rb:1:in `<top (required)>'
        from C:/Tools/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Tools/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
...
```

<details>
<summary>Info about my environment</summary>

`bundler env`
## Environment

```
Bundler   1.14.6
Rubygems  2.5.2
Ruby      2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
Git       2.11.0.windows.1
Platform  x86-mingw32
```
</details>

**Comment by mfazekas** [comment]
Have you tried recent net-ssh versions 4.*?

**Comment by ccoenen** [comment]
I'm very sorry for the confusion. Apparently my Gemfile.lock specified an ancient version of net-ssh.
