### ISSUE TITLE
Files are listing as junk characters

### ISSUE THREAD

**Issue by lakshmi2703** [net-ssh/net-sftp#66]
I am trying to list directory, but it displayed as junk characters. However the same site working without any issues with perl, php 
Sample code: 
Net::SFTP.start(host, username, :password => password, :port => 22) do |sftp|
      sftp.dir.foreach(folder) do |entry|
        next if (entry.name == '..' || entry.name == '.')
        puts entry.name
       end
end
I am getting like this:
epubtesepubtest��Y��dY��Y��..�epubtesepubtestA�Y��Y�\�Y�I`

 If I code entry.longname
I get exception like this:
/home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/protocol/04/name.rb:59:in `%': can't convert nil into Integer (TypeError)
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/protocol/04/name.rb:59:in `longname'
	from sftp_test1.rb:34:in `block (2 levels) in <main>'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/operations/dir.rb:33:in `block in foreach'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/operations/dir.rb:33:in `each'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/operations/dir.rb:33:in `foreach'
	from sftp_test1.rb:31:in `block in <main>'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `call'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `block in do_version'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `each'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `do_version'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:909:in `when_channel_polled'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/channel.rb:320:in `call'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/channel.rb:320:in `process'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:238:in `block in ev_preprocess'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:529:in `each'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:529:in `each_channel'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:238:in `ev_preprocess'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:216:in `process'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:787:in `connect!'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp.rb:32:in `start'
	from sftp_test1.rb:29:in `<main>'

**Comment by menge101** [comment]
I am also seeing this problem.

**Comment by heatlill** [comment]
Hello,
For what its worth I found this...
https://stackoverflow.com/questions/42124883/broken-filenames-with-ruby-when-connected-to-sftp-version-5

In a nut shell if a particular server is using a protocol version > 3 you can see this behavior (corrupted filenames).  I applied the fix (aka hack) of setting the HIGHEST_PROTOCOL_VERSION_SUPPORTED variable to 3 in sftp/session.rb locally and the issue was resolved.  Obviously if you deploy this to third party hosting you can't change the source code but at least you can test it.

**Comment by thbar** [comment]
This seems to be a duplicate of https://github.com/net-ssh/net-sftp/issues/78.

**Comment by thbar** [comment]
Net::SFTP v3.0.0 (published a few days ago) now allows (via https://github.com/net-ssh/net-sftp/pull/107) to do specify the protocol directly via `Net::SFTP.start`:

```ruby
Net::SFTP.start(host, user, ssh_options, {version: 3}) do
  # SNIP
end
```

@lakshmi2703 could you please try out?
