### ISSUE TITLE
Can't Download Multiple Files

### ISSUE THREAD

**Issue by Buullo** [net-ssh/net-sftp#84]
I used download multiple files.

  Net::SFTP.start(host, user, port: port, password: password) do |sftp|
    path = Rails.root.join('tmp', 'test')
    FileUtils.mkdir_p path
    sftp.dir.glob(remote_path, "*test*.zip") do |entry|
      filenames << entry.name
    end

    dls = filenames.map do |filename|
      sftp.download("#{remote_path}/#{filename}", (path + filename).to_s)
    end
    dls.each { |d| d.wait }
  end

And I got the error.
RuntimeError: open {remote_file}: failure (4)
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-sftp-2.1.2/lib/net/sftp/operations/download.rb:307:in `on_open'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `respond_to'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:948:in `dispatch_request'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:911:in `when_channel_polled'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-ssh-5.0.2/lib/net/ssh/connection/channel.rb:324:in `process'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:250:in `block in ev_preprocess'
	from org/jruby/RubyHash.java:1344:in `each'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:540:in `each_channel'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:250:in `ev_preprocess'
	from org/jruby/RubyArray.java:1734:in `each'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-ssh-5.0.2/lib/net/ssh/connection/event_loop.rb:101:in `ev_preprocess'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-ssh-5.0.2/lib/net/ssh/connection/event_loop.rb:29:in `process'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:228:in `process'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:181:in `block in loop'
	from org/jruby/RubyKernel.java:1296:in `loop'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:181:in `loop'
... 18 levels...
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:181:in `loop'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:787:in `connect!'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/net-sftp-2.1.2/lib/net/sftp.rb:32:in `start'
	from (irb):90:in `<eval>'
	from org/jruby/RubyKernel.java:995:in `eval'
	from org/jruby/RubyKernel.java:1296:in `loop'
	from org/jruby/RubyKernel.java:1115:in `catch'
	from org/jruby/RubyKernel.java:1115:in `catch'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/khunat/.rbenv/versions/jruby-9.1.5.0/lib/ruby/gems/shared/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<main>'
	from org/jruby/RubyKernel.java:956:in `require'
	from bin/rails:4:in `<main>'

OR I used this code.

  Net::SFTP.start(host, user, port: port, password: password) do |sftp|
    sftp.dir.glob(remote_path, "*Commission*.zip") do |entry|
      path = Rails.root.join('tmp', 'test')
      FileUtils.mkdir_p path
      sftp.download!("#{remote_path}/#{entry.name}", (path + entry.name).to_s)
    end
  end

I got same error too.

**Comment by jkarnesPerfectCube** [comment]
I don't see you checking to make sure that the filenames are, in fact, Files.

I have received this error when attempting to treat a directory as a file on accident. Can you please list the content of `filenames`?
