### ISSUE TITLE
How can I see a response from the server when authentication fails?

### ISSUE THREAD

**Issue by HarlemSquirrel** [net-ssh/net-sftp#90]
In following [this Everbridge guide](https://support.everbridge.com/articles/Technical_Support/Everbridge-Suite-Winter-2018-SFTP-Security-Upgrade-FAQ) I am able to get the following message even with permission denied.

```
➤  sftp sftp-test@sftp-conn-test.everbridge.net

     ____             __       _    __           ____
    / __/  _____ ____/ /  ____(_)__/ /__ ____   /  _/__  ____
   / _/| |/ / -_) __/ _ \/ __/ / _  / _ `/ -_) _/ // _ \/ __/
  /___/|___/\__/_/ /_.__/_/ /_/\_,_/\_, /\__/ /___/_//_/\__(_)
                                   /___/
           _______. _______ .___________..______    
          /       ||   ____||           ||   _  \   
         |   (----`|  |__   `---|  |----`|  |_)  |  
          \   \    |   __|      |  |     |   ___/   
      .----)   |   |  |         |  |     |  |       
      |_______/    |__|         |__|     | _|       
                                                    
      .___________. _______     _______.___________.
      |           ||   ____|   /       |           |
      `---|  |----`|  |__     |   (----`---|  |----`
          |  |     |   __|     \   \       |  |     
          |  |     |  |____.----)   |      |  |     
          |__|     |_______|_______/       |__|     

  ***********************************************************************
  **    If you are seeing this message, connectivity has succeeded!    **
  **                ATTEMPTS TO LOGIN WILL NOT SUCCEED                 **
  ***********************************************************************

  This system is for the use of connectivity testing purpose only.


sftp-test@sftp-conn-test.everbridge.net: Permission denied (publickey).
Connection closed
```

Using Ruby and this gem I have this so far.
```
2.6.1 :001 > HOSTNAME = 'sftp-conn-test.everbridge.net'
 => "sftp-conn-test.everbridge.net" 
2.6.1 :002 > USERNAME = 'sftp-test'
 => "sftp-test" 
2.6.1 :003 > require 'net/sftp'
 => true 
2.6.1 :004 > Net::SFTP.start(HOSTNAME, USERNAME, :password => nil) do |sftp|
2.6.1 :005 >     sftp.dir.foreach("/") do |entry|
2.6.1 :006 >             puts entry.longname
2.6.1 :007?>         end
2.6.1 :008?>   end
Traceback (most recent call last):
        6: from /home/kem2028/.rvm/rubies/ruby-2.6.1/bin/irb:23:in `<main>'
        5: from /home/kem2028/.rvm/rubies/ruby-2.6.1/bin/irb:23:in `load'
        4: from /home/kem2028/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        3: from (irb):4
        2: from /home/kem2028/.rvm/gems/ruby-2.6.1/gems/net-sftp-3.0.0.beta1/lib/net/sftp.rb:31:in `start'
        1: from /home/kem2028/.rvm/gems/ruby-2.6.1/gems/net-ssh-5.1.0/lib/net/ssh.rb:259:in `start'
Net::SSH::AuthenticationFailed (Authentication failed for user sftp-test@sftp-conn-test.everbridge.net
```

**Comment by HarlemSquirrel** [comment]
I've got it.

```ruby
require 'net/sftp'

HOSTNAME = 'sftp-conn-test.everbridge.net'
USERNAME = 'sftp-test'

Net::SFTP.start(HOSTNAME, USERNAME, verbose: Logger::DEBUG) do |sftp|
  # list the entries in a directory
  sftp.dir.foreach("/") do |entry|
    puts entry.longname
  end
end
```

```
➤  ruby tmp/everbridge-sftp-test.rb
D, [2019-02-15T14:41:56.552177 #17353] DEBUG -- net.ssh.transport.session[8431f4]: establishing connection to sftp-conn-test.everbridge.net:22
D, [2019-02-15T14:41:56.648493 #17353] DEBUG -- net.ssh.transport.session[8431f4]: connection established
I, [2019-02-15T14:41:56.648809 #17353]  INFO -- net.ssh.transport.server_version[849edc]: negotiating protocol version
D, [2019-02-15T14:41:56.648905 #17353] DEBUG -- net.ssh.transport.server_version[849edc]: local is `SSH-2.0-Ruby/Net::SSH_5.1.0 x86_64-linux'
D, [2019-02-15T14:41:56.672493 #17353] DEBUG -- net.ssh.transport.server_version[849edc]: remote is `SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.7'
W, [2019-02-15T14:41:56.672993 #17353]  WARN -- net.ssh.transport.algorithms[84de9c]: unsupported algorithm: `["aes256-gcm@openssh.com", "chacha20-poly1305@openssh.com", "aes128-gcm@openssh.com"]'
W, [2019-02-15T14:41:56.673202 #17353]  WARN -- net.ssh.transport.algorithms[84de9c]: unsupported algorithm: `["hmac-sha2-256-etm@openssh.com", "hmac-sha1-etm@openssh.com", "umac-128-etm@openssh.com", "hmac-sha2-512-etm@openssh.com", "umac-128@openssh.com"]'
I, [2019-02-15T14:41:56.680286 #17353]  INFO -- net.ssh.transport.algorithms[84de9c]: sending KEXINIT
D, [2019-02-15T14:41:56.682170 #17353] DEBUG -- socket[842b50]: queueing packet nr 0 type 20 len 724
D, [2019-02-15T14:41:56.682934 #17353] DEBUG -- socket[842b50]: sent 728 bytes
D, [2019-02-15T14:41:56.694069 #17353] DEBUG -- socket[842b50]: read 512 bytes
D, [2019-02-15T14:41:56.694638 #17353] DEBUG -- socket[842b50]: received packet nr 0 type 20 len 508
I, [2019-02-15T14:41:56.694889 #17353]  INFO -- net.ssh.transport.algorithms[84de9c]: got KEXINIT from server
I, [2019-02-15T14:41:56.695240 #17353]  INFO -- net.ssh.transport.algorithms[84de9c]: negotiating algorithms
D, [2019-02-15T14:41:56.695605 #17353] DEBUG -- net.ssh.transport.algorithms[84de9c]: negotiated:
* kex: ecdh-sha2-nistp521
* host_key: ecdsa-sha2-nistp256
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-256
* hmac_server: hmac-sha2-256
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2019-02-15T14:41:56.695800 #17353] DEBUG -- net.ssh.transport.algorithms[84de9c]: exchanging keys
D, [2019-02-15T14:41:56.699091 #17353] DEBUG -- socket[842b50]: queueing packet nr 1 type 30 len 148
D, [2019-02-15T14:41:56.699264 #17353] DEBUG -- socket[842b50]: sent 152 bytes
D, [2019-02-15T14:41:56.809708 #17353] DEBUG -- socket[842b50]: read 376 bytes
D, [2019-02-15T14:41:56.809813 #17353] DEBUG -- socket[842b50]: received packet nr 1 type 31 len 356
D, [2019-02-15T14:41:56.811088 #17353] DEBUG -- socket[842b50]: queueing packet nr 2 type 21 len 20
D, [2019-02-15T14:41:56.811175 #17353] DEBUG -- socket[842b50]: sent 24 bytes
D, [2019-02-15T14:41:56.811245 #17353] DEBUG -- socket[842b50]: received packet nr 2 type 21 len 12
D, [2019-02-15T14:41:56.811540 #17353] DEBUG -- net.ssh.authentication.session[9758ec]: beginning authentication of `sftp-test'
D, [2019-02-15T14:41:56.811657 #17353] DEBUG -- socket[842b50]: queueing packet nr 3 type 5 len 28
D, [2019-02-15T14:41:56.811693 #17353] DEBUG -- socket[842b50]: sent 64 bytes
D, [2019-02-15T14:41:56.899378 #17353] DEBUG -- socket[842b50]: read 64 bytes
D, [2019-02-15T14:41:56.899885 #17353] DEBUG -- socket[842b50]: received packet nr 3 type 6 len 28
D, [2019-02-15T14:41:56.900216 #17353] DEBUG -- net.ssh.authentication.session[9758ec]: trying none
D, [2019-02-15T14:41:56.900671 #17353] DEBUG -- socket[842b50]: queueing packet nr 4 type 50 len 60
D, [2019-02-15T14:41:56.900890 #17353] DEBUG -- socket[842b50]: sent 96 bytes
D, [2019-02-15T14:41:56.932070 #17353] DEBUG -- socket[842b50]: read 1456 bytes
D, [2019-02-15T14:41:56.932630 #17353] DEBUG -- socket[842b50]: received packet nr 4 type 53 len 1356
I, [2019-02-15T14:41:56.932910 #17353]  INFO -- net.ssh.authentication.session[9758ec]: 
     ____             __       _    __           ____
    / __/  _____ ____/ /  ____(_)__/ /__ ____   /  _/__  ____
   / _/| |/ / -_) __/ _ \/ __/ / _  / _ `/ -_) _/ // _ \/ __/
  /___/|___/\__/_/ /_.__/_/ /_/\_,_/\_, /\__/ /___/_//_/\__(_)
                                   /___/
           _______. _______ .___________..______    
          /       ||   ____||           ||   _  \   
         |   (----`|  |__   `---|  |----`|  |_)  |  
          \   \    |   __|      |  |     |   ___/   
      .----)   |   |  |         |  |     |  |       
      |_______/    |__|         |__|     | _|       
                                                    
      .___________. _______     _______.___________.
      |           ||   ____|   /       |           |
      `---|  |----`|  |__     |   (----`---|  |----`
          |  |     |   __|     \   \       |  |     
          |  |     |  |____.----)   |      |  |     
          |__|     |_______|_______/       |__|     

  ***********************************************************************
  **    If you are seeing this message, connectivity has succeeded!    **
  **                ATTEMPTS TO LOGIN WILL NOT SUCCEED                 **
  ***********************************************************************

  This system is for the use of connectivity testing purpose only.



D, [2019-02-15T14:41:56.933373 #17353] DEBUG -- socket[842b50]: received packet nr 5 type 51 len 28
D, [2019-02-15T14:41:56.933562 #17353] DEBUG -- net.ssh.authentication.session[9758ec]: allowed methods: publickey
D, [2019-02-15T14:41:56.933745 #17353] DEBUG -- net.ssh.authentication.methods.none[9741e0]: none failed
D, [2019-02-15T14:41:56.933930 #17353] DEBUG -- net.ssh.authentication.session[9758ec]: trying publickey
D, [2019-02-15T14:41:56.934717 #17353] DEBUG -- net.ssh.authentication.agent[988fc8]: connecting to ssh-agent
D, [2019-02-15T14:41:56.935275 #17353] DEBUG -- net.ssh.authentication.agent[988fc8]: sending agent request 1 len 44
D, [2019-02-15T14:41:56.936371 #17353] DEBUG -- net.ssh.authentication.agent[988fc8]: received agent packet 5 len 1
D, [2019-02-15T14:41:56.936545 #17353] DEBUG -- net.ssh.authentication.agent[988fc8]: sending agent request 11 len 0
D, [2019-02-15T14:41:56.937327 #17353] DEBUG -- net.ssh.authentication.agent[988fc8]: received agent packet 12 len 866
D, [2019-02-15T14:41:56.938395 #17353] DEBUG -- net.ssh.authentication.methods.publickey[9897c0]: trying publickey (c6:fa:3f:74:bd:35:07:15:8c:cb:63:f8:6c:70:80:65)
D, [2019-02-15T14:41:56.939016 #17353] DEBUG -- socket[842b50]: queueing packet nr 5 type 50 len 604
D, [2019-02-15T14:41:56.939247 #17353] DEBUG -- socket[842b50]: sent 640 bytes
D, [2019-02-15T14:41:56.967640 #17353] DEBUG -- socket[842b50]: read 64 bytes
D, [2019-02-15T14:41:56.968260 #17353] DEBUG -- socket[842b50]: received packet nr 6 type 51 len 28
D, [2019-02-15T14:41:56.968632 #17353] DEBUG -- net.ssh.authentication.session[9758ec]: allowed methods: publickey
E, [2019-02-15T14:41:56.968942 #17353] ERROR -- net.ssh.authentication.session[9758ec]: all authorization methods failed (tried none, publickey)
Traceback (most recent call last):
	2: from tmp/everbridge-sftp-test.rb:16:in `<main>'
	1: from /home/$USER/.rvm/gems/ruby-2.6.1/gems/net-sftp-3.0.0.beta1/lib/net/sftp.rb:31:in `start'
/home/$USER/.rvm/gems/ruby-2.6.1/gems/net-ssh-5.1.0/lib/net/ssh.rb:259:in `start': Authentication failed for user sftp-test@sftp-conn-test.everbridge.net (Net::SSH::AuthenticationFailed)
```
